#!/bin/bash
set -e

wget -q -O openrefine-2.8.tar.gz https://github.com/OpenRefine/OpenRefine/releases/download/2.8/openrefine-linux-2.8.tar.gz
tar xzf openrefine-2.8.tar.gz

mkdir -p $HOME/openrefine

mkdir -p $HOME/.jupyter/

#This script runs in $HOME rather than $HOME/binder
mv open-refine-logo.svg $HOME/.jupyter/

#And enable...
jupyter labextension install jupyterlab-server-proxy

#pip install https://github.com/betatim/nbserverproxy/archive/master.zip
#jupyter serverextension enable --py nbserverproxy

#pip install -e.
#
#jupyter serverextension enable  --user --py openrefine
#jupyter nbextension     install --user --py nbopenrefineproxy
#jupyter nbextension     enable  --user --py nbopenrefineproxy
